; ################################### Taskbar App List configuration ###################################
[Taskbar.AppList]

; Changing visibility of the clock
visible = True

; Widget position on the panel
; 0% = left, 50% = center, 100% = right
position = 50%

; Widget align
; 0% - left, 50% - center, 100% - right
align = 50%

; Icon size
icon_size = 18

; Icon padding
paddings = 8

; Spacing between icons
spacing = 10
; ######################################################################################################