[Info]
name = Default Spectrum Analyzer
author = Ninawe
version = 1.0

; /// init values. Do not change if you don't know what you're doing
[Layout]
min_width = 1920
min_height = 350

[Spectrum.Preferences]
; /// Sample rate setting
; may be useful if you want to cut off a frequency range completely, rather than just cut off the high frequencies
; Changing this parameter also change chunk_size for better experience
sample_rate = 44100

; /// The number of samples taken for analysis
chunk_size = 2048

; /// Number of bands (vertical lines)
bands = 128

; /// Scale
; Possible values: log, linear
scale = log

; /// Frequency cut-out
; may be useful for cutting off unused infra/ultra frequencies
min_freq = 30
max_freq = 18000

; /// Gain/Sensitivity
; It can be useful if you need to make the peaks of the graph smaller/larger
sensitivity = 5

; /// Smoothing 
; Frequency smoothing. It smooths and averages adjacent frequencies to remove "spikes" in the spectrum.
smoothing = 0

; /// Refresh rate
; By changing this parameter you can increase or decrease the spectrum/physics update frequency.
spectrum_refresh_rate = 60
physics_refresh_rate = 30

; /// Animation speed coefficients
; when atack (volume going up):
attack = 1
; when roll-off (volume going down)
roll_off = 0.3

; /// Spectrum EQ
; By increasing the starting value, you can either increase or decrease the sensitivity to low frequencies. The same applies to the end value.
eq_start_coef = 1
eq_end_coef = 2

; /// Peak holds (falling caps) toggle
peak_holds_enabled = True

[Spectrum.Style]
; /// Padding between bands
paddings = 5

; /// Bands color
color = #AAFFFFFF

; /// Min height for band in silent mode (0 to 100 float)
band_min_height = 1

; /// Peak holds styles
peak_holds_color = #FFFFFFFF
peak_holds_falloff = 0.5
peak_holds_height = 1
