[Info]
name = Default Spectrum Analyzer
author = Ninawe
version = 1.0

; /// init values. Do not change if you don't know what you're doing
[Layout]
min_width = 800
min_height = 200

[Spectrum.Preferences]
; /// Sample rate setting
; may be useful if you want to cut off a frequency range completely, rather than just cut off the high frequencies
; Changing this parameter also change chunk_size for better experience
sample_rate = 192000

; /// The number of samples taken for analysis
chunk_size = 8192

; /// Number of bands (vertical lines)
bands = 84

; /// Scale
; Possible values: log, linear
scale = log

; /// Frequency cut-out
; may be useful for cutting off unused infra/ultra frequencies
min_freq = 63
max_freq = 18000

; /// Gain/Sensitivity
; It can be useful if you need to make the peaks of the graph smaller/larger
sensitivity = 2

; /// Smoothing 
; Frequency smoothing. It smooths and averages adjacent frequencies to remove "spikes" in the spectrum.
smoothing = 5

; /// Frame per second (FPS)
; uhhhh... You know...
fps = 60

; /// Animation speed coefficients
; when atack (volume going up):
attack = 2
; when roll-off (volume going down)
roll_off = 0.3

; /// Spectrum EQ
; By increasing the starting value, you can either increase or decrease the sensitivity to low frequencies. The same applies to the end value.
eq_start_coef = 0.75
eq_end_coef = 2

; /// Peak holds (falling caps) toggle
peak_holds_enabled = False

[Spectrum.Style]
; /// Padding between bands
paddings = 5

; /// Bands color
color = #FFFFFFFF

; /// Min height for band in silent mode (0 to 100 float)
band_min_height = 5

; /// Peak holds styles
peak_holds_color = #FFFFFFFF
peak_holds_falloff = 0.7
peak_holds_height = 5