; ############################################# Theme info #############################################
[Theme]
name = Default Dark
version = 1.0
author = Ninawe dev.
description = Standard dark theme
; ######################################################################################################

; ############################################### Globals ##############################################
[Global]
font_family = resources\font\font.ttf
font_color = #FFFFFF
font_size = 11
font_shadow = True
; ######################################################################################################

; ######################################## Desktop configuration #######################################
[Desktop]
; /// Path to wallpaper
; Use only directory if you want to use carousel, otherwise full path to file
wallpaper_path = resources\wallpapers

; /// Wallpaper mode
; Possible values:
; 	cover - stretch it to the entire diagonal of the workspace and cut off the excess
;	contain - fit into the workspace
wallpaper_mode = cover

; /// Wallpaper carousel settings
wallpaper_carousel = False
carousel_interval_min = 0.05
carousel_shuffle = False
wallpaper_transition_ms = 500

; /// Window margins
; Sets the margins of the icon container, starting from the edges of the screen
; Possible values: px
window_margin_x = 0
window_margin_y = 0

; /// Group selection color (highlighting)
group_selection_background = #55FFFFFF
group_selection_border = #66FFFFFF

; /// Group selection border settings
; Possible values: px
group_selection_border_width = 0
group_selection_border_radius = 5
; ######################################################################################################

; ##################################### Desktop Icon Configuration #####################################
[Desktop.Icon]
; /// Bitmap size
; Sets the icon size
bitmap_size = 48

; /// Item width/height
; Sets the container size for the icon.
item_width = 80
item_height = 90

; /// Gap between icons
spacing_x = 0
spacing_y = 0

; /// Show/hide icon label
; Possible values:
;	True - show icon label
;	False - hide icon label
icon_label_status = True

; /// Label font
icon_label_font_family = Segoe UI

; /// Label font size
; Possible values: px
icon_label_font_size = 11

; /// Label letters in row compensator
; It will be useful in cases when fonts are too wide or their size is not determined correctly.
icon_label_compensator = 1

; /// Icon container border
; Possible values: px
icon_container_border = 0
icon_container_border_radius = 3

; /// Icon container colors
; Hover state
icon_hover_background = #44FFFFFF
icon_hover_border = #55FFFFFF
; Selected state
icon_selected_background = #55FFFFFF
icon_selected_border = #66FFFFFF
; Hover on selected state
icon_hover_on_selected_background = #66FFFFFF
icon_hover_on_selected_border = #77FFFFFF
; Drop state
icon_drop_background = #77FFFFFF
icon_drop_border = #88FFFFFF
; ######################################################################################################

; ##################################### Context Menu Configuration #####################################
[ContextMenu]
; /// Menu configuration (all)
; Background color (argb)
menu_bg_color = #BB111111

; Border configuration
; Possible values: color - argb, width/radius - px
menu_border_color = #55FFFFFF
menu_border_width = 1
menu_border_radius = 8

; Paddings (px)
menu_padding = 5

; /// Item configuration
; Possible values: color - argb, paddings/margins - px
item_selected_bg_color = #44FFFFFF
item_padding_x = 30
item_padding_y = 6
item_margin = 2

; /// Separator configuration
separator_bg_color = #22FFFFFF
separator_height = 1
separator_margin_x = 10
separator_margin_y = 4

# Font configuration
font_size = default 
font_color = default
font_family = Segoe UI
; ######################################################################################################

; ######################################## Taskbar configuration #######################################
[Taskbar]
; /// Orientation of the panel
; possible values: horizontal, vertical
orientation = horizontal

; /// Width and height of the panel
; possible values: %, px
width = 99%
height = 30px

; /// Position of the panel on the screen
; possible values: %, px
position_x = 50%
position_y = 2%

; /// The selectable offset of the panel. Affects how the panel will be aligned.
; possible values: %, px
anchor_x = 50%
anchor_y = 50%

; /// Panel borders
border_radius_px = 10
border_width_px = 1
argb_border_color = #5BFFFFFF

; /// Panel color
argb_color = #55666666

; /// Panel blur
; Due to some limitations and compatibility issues, this option does not support border_radius
; Use alpha channel on argb_color to make blur more visible
; If you use power saving mode, the blur may not render correctly
blur_enabled = True

; /// Blur type
; Possible values:
;	0 - default
;	1 - acrylic
blur_mode = 0

; /// Active taskbar widgets
; Use widget folder name to set widget
active_widgets = defaultClock, launchpadButton, appList
; ######################################################################################################

; ####################################### PowerMenu configuration ######################################
[PowerMenu]
; /// Fullscreen
; Possible values: 
;		False - PowerMenu is just panel with buttons
;		True - PowerMenu is fullscreen window
fullscreen = True

; /// Use background color on fullscreen
use_bg_color = True

; /// Menu layout
; Possible values:
; 	horizontal - arrange buttons horizontally
; 	vertical - arrange buttons vertically
menu_layout = horizontal

; /// Button container width/height
; Write 0 everywhere if you want the program to set the minimum possible values automatically.
width = 0
height = 0

; /// PowerMenu container background color
argb_container_color = #99666666

; /// PowerMenu double container background toggle
; It can be useful if you want to make a border -> colored padding between a container and border -> container
double_container_bg = True

; /// Double container background accent. 
; Possible values:
;	bg - pick argb_background_color as double container background accent
;	container - pick argb_container_color as double container background accent
double_container_bg_accent = bg

; /// PowerMenu fullscreen background color
argb_background_color = #22FF0000

; /// Background blur
; Due to some limitations and compatibility issues, this option does not support border_radius without fullscreen
; Use alpha channel on argb_color to make blur more visible
; If you use power saving mode, the blur may not render correctly
blur_enabled = True

; /// Blur mode
; Possible values:
; 	0 - default
;	1 - acrylic
blur_mode = 1

; /// Container margins
margins = 15

; /// Container paddings
paddings = 10

; /// Button size
button_size = 100

; /// Panel border
argb_border_color = #FFFFFFFF
border_radius = 50
border_width_px = 5

; /// Space between buttons
spacing = 15

; /// .SVG icons dir
; USE THE BUTTON ID AS THE FILE NAME!!! In this case, the program will find the icons automatically
icons_dir = resources\pm_icons

; /// Button colors
button_color = #55000000
hover_color = #AA999999
pressed_color = #FFFFFFFF

; /// Button border
button_border_width = 0
button_border_color = #FFFFFFFF
; ######################################################################################################

; ####################################### Launchpad configuration ######################################
[Launchpad]
fullscreen = true
fullscreen_color = #22000000

blur_enabled = true
blur_mode = 1

main_container_width = 50%
main_container_height = 60%
main_container_columns = 6

main_container_bg_color = #88000000
main_container_border_color = #FFFFFF
main_container_border_radius = 25
main_container_border_width = 1

; #################################### Launchpad Misc configuration ####################################

scroll_color = #33FFFFFF
scroll_hover_color = #66FFFFFF
scroll_border_radius = 4
scoll_width = 8

searchbar_border_width = 1
searchbar_border_radius = 10
searchbar_text_color = #FFFFFF
searchbar_text_size = 16

searchbar_default_bg_color = #22FFFFFF
searchbar_default_border_color = #77FFFFFF

searchbar_focus_bg_color = #33FFFFFF
searchbar_focus_border_color = #99FFFFFF

; ######################################################################################################

; #################################### Launchpad Item configuration ####################################
[Launchpad.Item]

item_container_width = 120
item_container_height = 140

; /// Item container style settings

item_container_border_radius = 15
item_container_border_width = 1

item_container_default_bg_color = transparent
item_container_default_border_color = transparent

item_container_hover_bg_color = #44FFFFFF
item_container_hover_border_color = #55FFFFFF

item_container_pressed_bg_color = #66FFFFFF
item_container_pressed_border_color = #77FFFFFF

; /// Icon container style settings

item_container_icon_border_width = 0
item_container_icon_border_radius = 15

item_container_icon_bg_color = #22FFFFFF
item_container_icon_border_color = transparent

; /// Icon settings

item_icon_size = 48
item_icon_padding = 24

; ######################################################################################################