##################################### Taskbar Clock configuration #####################################
[Taskbar.Clock]

; Changing visibility of the clock
visible = True

; Font properties
font_family = resources\font\font.ttf
font_color = #FFFFFF
font_size = 7
font_shadow = True

; Clock width
width = 0

; R/L margins
margin_left = 0
margin_right = 0

; Clock position on the panel
; 0% = left, 50% = center, 100% = right
position = 99%

; Align clock on their width
; 0% - left, 50% - center, 100% - right
align = 100%

; Clock time format
time_format = HH:mm\ndd.MM.yy
; ######################################################################################################