; ############################### Taskbar Launchpad Button configuration ###############################
[Taskbar.LaunchpadButton]

; Changing visibility of the clock
visible = True

; Button position on the panel
; 0% = left, 50% = center, 100% = right
position = 0.25%

; Button align
; 0% - right, 50% - center, 100% - left
align = 0%

; Icons dir
default = resources\images\state_default.png
hover = resources\images\state_hover.png
active = resources\images\state_active.png
; ######################################################################################################